# Generated by Django 4.2 on 2025-12-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerceApp', '0003_productabout_productdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
