# Generated by Django 4.2 on 2025-12-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerceApp', '0005_alter_productreviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='merchantuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Automatically calculated average rating from product reviews', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
