# Generated by Django 4.2 on 2025-12-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerceApp', '0006_alter_adminuser_id_alter_customeruser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Automatically calculated average rating from product reviews', max_digits=3, null=True),
        ),
    ]
