# Generated by Django 4.2 on 2025-12-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerceApp', '0007_alter_products_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Automatically calculated average rating from product reviews', max_digits=3),
        ),
    ]
